### ISSUE TITLE
NO.11  自社発送のオーダーレポートも取込したい

### ISSUE THREAD

**Issue by Realizarcompany** [Order-management-system/OMS#12]
現在、オーダーレポートをダウンロードしてから、
手動でMCF（FBAに預けて、楽天やヤフショなどにAmazonが発送してくれるシステム）の注文や自社発送の注文を削除して取込している状況です。

これをオーダーレポートを編集せずに取込できるようにしたいです。

**Comment by haya-work** [comment]
対応自体は可能と考えています。

工数は概算ですが、一旦10人日～15人日程度でお考え頂きたく。
修正範囲は、現状でわかっている箇所で以下の通りです。
・オーダー復帰、キャンセル処理
・在庫割り当て処理
・発注データ作成処理
・出庫処理
・発送処理
・各種通知機能

この対応に対する注意点があります。
sales-channel が Non-Amazon のオーダーは対応完了後も取込する事は出来ません。
理由としては、通貨や売上金額や税等の情報を持たないデータの為です。

ただ、Non-Amazonのオーダーも自社で発送する為に管理が必要で、
利益情報は無視して取込したいという事であれば、そういった対応も可能とは思われますのでご相談ください。

オーダーIDの例
S03-0313021-7783004
S03-7838124-5734238

**Comment by Realizarcompany** [comment]
S03-0313021-7783004
S03-7838124-5734238
は
MCF（FBAに預けて、楽天やヤフショなどにAmazonが発送してくれるシステム）の注文ですね。

SKUが
6jp000000242
6jp000000244

のものになります。

こちらは、楽天やヤフーショッピングで入った注文に、FAmazonスタッフがFBAに在庫している商品を発送してくれる注文ですが、手数料が高いわりにそれほど売れないので...

自社発送も現段階では、不良在庫をはくのに使用している状況でして。
いつかは取り組みたいですが、現時点では少し、費用に対して効果を検討したいです。
ちなみに、
10人日～15人日というのは時間で表すとどれくらいでしょうか？

**Comment by haya-work** [comment]
1人日は一人の人間が１日働く時間で＝8ｈと計算されます。
ですので、10日～15日働くということで80～120hという計算になります。
以上、よろしくお願いします。

**Comment by Realizarcompany** [comment]
分かりました。
ありがとうございます。
この件は手作業で行を削除するという、手間になりますが、その運用を少し続けたいと思います。
MCFや自社発送は始めたばかりなので、今後の売れ行きを見つつ、資金を貯めるなどして、一度、様子を見ることにします。
またお願いするときは早かれ遅かれ来ると思います。
よろしくお願いします。
