### ISSUE TITLE
NO.12　発注登録を分かれるようにしたい

### ISSUE THREAD

**Issue by Realizarcompany** [Order-management-system/OMS#13]
先日のお話ですと、発注登録は分かれる？ということだったかと思うのですが、一緒になるようです。
自社発送時ですと、福山さん1人が発注だったので、そのような仕様だったかと思いますが、現体制では、2人または3人での発注を想定していまして、取り急ぎではないのですが、この発注登録を分かれる仕様にするには、どれくらいの工数必要でしょうか？

https://www.dropbox.com/s/f4hgw3zuy431nq4/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202023-07-07%20125756.png?dl=0

https://www.dropbox.com/s/i5xu37bfkllr9oo/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202023-07-07%20125704.png?dl=0

**Comment by haya-work** [comment]
発注後のデータは入荷に利用する為、デフォルトは発注先で纏まる仕様となっていますが、
発注単位で入荷処理を行いたい場合は、
入荷条件欄にある、入荷対象のプルダウンで「発注単位」を選択して検索することで、
発注単位で表示されるようになっています。

以上よろしくお願いします。

**Comment by haya-work** [comment]
![無題](https://github.com/Order-management-system/OMS/assets/73450595/c2a81144-e386-4314-876d-fdf29886ad77)

**Comment by Realizarcompany** [comment]
分かりました。
すでにこのようにソートをかけることで
分けれるなら、解決です。
ありがとうございます。
