### ISSUE TITLE
NO.13 為替の自動取得をしたい

### ISSUE THREAD

**Issue by Realizarcompany** [Order-management-system/OMS#14]
Google 検索の　「ドル　円」
などで構いませんので、為替の自動取得できるようにしたいです。

**Comment by haya-work** [comment]
調査があまりできていませんので、一旦は10h程で見積もらせてください。場合によっては大きく少なくなることもありますが、逆もあるかと思います。

**Comment by haya-work** [comment]
為替情報の自動取得処理実装が完了致しました。
利用APIはalpha-vantage-apiです。１日に１００回取得可能です。それ以上は有料契約が必要です。
