### ISSUE TITLE
NO.15 在庫ページに　100商品以上の商品を表示するには

### ISSUE THREAD

**Issue by Realizarcompany** [Order-management-system/OMS#16]

**Comment by haya-work** [comment]
実装方法としては２通りあります。
①単純に表示件数を増やす方法。
②ページ切り替え機能を実装する方法。

①の場合工数は非常に少なく済みますが、限度があります。またサーバへの負荷が大きくなり表示まで時間が掛ります。
　概算工数は0.5h～1h程度
②の場合一度に読み込む件数は１００件のままでページ切り替えを行うことで次の１００件を読み込む方式です。実装に工数がある程度かかります。
　概算工数は10h～15h程と思われます。
