### ISSUE TITLE
NO.19　消費期限の追加

### ISSUE THREAD

**Issue by Realizarcompany** [Order-management-system/OMS#20]
食品や、消費期限がある商品を多く仕入れるようになり、消費期限の管理行いたいです。
具体的には、商品を入荷した際に、消費期限を入力する欄を追加していただきたいです。
項目を１つ追加するかたちになります。

**Comment by haya-work** [comment]
対応内容は以下の内容となります。
①DB設計変更
②マスタ登録画面インタフェース項目追加
③DB登録、更新、削除機能の修正
④在庫検索項目の追加
⑤在庫検索結果一覧の表示項目追加

その他、仕様検討、デバッグ作業、プログラムデプロイで1人日程と思われます。
よろしくお願いします。
