### ISSUE TITLE
NO.5 自社発送とFBAのハイブリッドのシステム利用

### ISSUE THREAD

**Issue by Realizarcompany** [Order-management-system/OMS#6]

**Comment by haya-work** [comment]
対応可能と思われます。
今回FBA取込機能を実装して、ある程度修正箇所が把握は出来たと考えております。
今回の修正工数と同等程度で対処出来るのではないかと見積もっています。
※響範囲が広いため、把握できていない修正で工数が膨らむ可能性はあります、ご了承ください。

**Comment by Realizarcompany** [comment]
わかりました。
ありがとうございます。
こちらまた、オンラインなどで詳細を伝えたり、お聞きしたりさせてください。
よろしくお願いします。

**Comment by haya-work** [comment]
以下のタスクと同様の対応となります。
https://github.com/Order-management-system/OMS/issues/12
