### ISSUE TITLE
NO.9 eBayのAPI連携

### ISSUE THREAD

**Issue by Realizarcompany** [Order-management-system/OMS#9]
以前、板垣とeBayのAPIの連携を設定していただいたように、
トークン情報などこちらで取得することはしますので、
そちらの設定をして、受発注がOMSに反映されるようにしたいです。

**Comment by Realizarcompany** [comment]
Developper account 更新方法
https://docs.google.com/document/d/13_NlTAIitgZvIcwxwowQPEBQ-Gepud7u41M-vdnTbt8/edit

eBay でのオペレーション側での更新方法は記録していました。

**Comment by haya-work** [comment]
eBayのオーダーレポート取込については、下記タスクへの回答内容と同じ対応が必要となります。
ご確認よろしくお願いします。
https://github.com/Order-management-system/OMS/issues/12

**Comment by Realizarcompany** [comment]
eBayはオーダーレポート取込ではなく、
上記のAPI連携でできたと思ったのですが、
いかがでしょうか？

**Comment by haya-work** [comment]
API連携でオーダーの取込は可能です。
取込後の処理はAmazonと同様になりますので、下記FBA対応のプログラム修正が必要になります。
https://github.com/Order-management-system/OMS/issues/12
